import { Browser } from 'types';

type Permissions = string[] | undefined;

const common = [
  'activeTab',
  'alarms',
  'bookmarks',
  'browsingData',
  'contextMenus',
  'cookies',
  'declarativeNetRequest',
  'declarativeNetRequestFeedback',
  'declarativeNetRequestWithHostAccess',
  'dns',
  'downloads',
  'downloads.open',
  'geolocation',
  'history',
  'identity',
  'idle',
  'management',
  'nativeMessaging',
  'notifications',
  'privacy',
  'proxy',
  'scripting',
  'search',
  'sessions',
  'storage',
  'tabs',
  'topSites',
  'unlimitedStorage',
  'webNavigation',
  'webRequest',
  'webRequestBlocking',
];

const permissions = {
  chrome: [
    ...common,
    'background',
    'accessibilityFeatures.modify',
    'accessibilityFeatures.read',
    'audio',
    'certificateProvider',
    'contentSettings',
    'declarativeContent',
    'debugger',
    'desktopCapture',
    'documentScan',
    'downloads.ui',
    'enterprise.deviceAttributes',
    'enterprise.hardwarePlatform',
    'enterprise.networkingAttributes',
    'enterprise.platformKeys',
    'favicon',
    'fileBrowserHandler',
    'fileSystemProvider',
    'fontSettings',
    'gcm',
    'loginState',
    'offscreen',
    'pageCapture',
    'platformKeys',
    'power',
    'printerProvider',
    'printing',
    'printingMetrics',
    'processes',
    'runtime',
    'sidePanel',
    'system.cpu',
    'system.display',
    'system.memory',
    'system.storage',
    'tabCapture',
    'tabGroups',
    'tts',
    'ttsEngine',
    'vpnProvider',
    'wallpaper',
    'webAuthenticationProxy',
    'webRequestAuthProvider',
  ],
  firefox: [
    ...common,
    'browserSettings',
    'captivePortal',
    'clipboardRead',
    'clipboardWrite',
    'contextualIdentities',
    'devtools',
    'find',
    'menus',
    'menus.overrideContext',
    'pkcs11',
    'tabHide',
    'theme',
    'webRequestFilterResponse',
    'webRequestFilterResponse.serviceWorkerScript',
  ],
  safari: [],
  edge: [],
};

const nonOptionalPermissions = {
  chrome: [
    'debugger',
    'declarativeNetRequest',
    'devtools',
    'experimental',
    'geolocation',
    'mdns',
    'proxy',
    'tts',
    'ttsEngine',
    'wallpaper',
  ],
  firefox: [
    'alarms',
    'dns',
    'identity',
    'search',
    'storage',
    'unlimitedStorage',
    'captivePortal',
    'contextualIdentities',
    'menus',
    'menus.overrideContext',
    'theme',
  ],
  safari: [],
  edge: [],
};

export const filterRequiredPermissions = ($permissions: Permissions, browser: Browser) => {
  return ($permissions || []).filter(permission => permissions[browser].includes(permission as never));
};

export const filterOptionalPermissions = ($permissions: Permissions, browser: Browser) => {
  filterRequiredPermissions($permissions, browser).filter(permission => !nonOptionalPermissions[browser].includes(permission as never));
};
