name: "Publish Stable Version"

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Build & Publish
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
          pnpm --filter "./packages/**" --filter "[origin/main]" publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
